trigger:
- main  # Change this to the name of your main branch

pr:
- '*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    echo Setting up Docker...
    curl -fsSL https://get.docker.com -o get-docker.sh
    sudo sh get-docker.sh
  displayName: 'Install Docker'

- script: |
    echo Logging in to DockerHub...
    docker login -u aadilsehrawat -p $(DOCKERHUB_PASSWORD)
  displayName: 'Docker Login'

- script: |
    echo Pulling Docker image...
    docker pull aadilsehrawat/aadils-docker-image
  displayName: 'Docker Pull'

- script: |
    echo Building Docker image...
    docker build -t my-webapp .
  displayName: 'Docker Build'

- script: |
    echo Pushing Docker image...
    docker tag my-webapp aadilsehrawat/aadils-docker-image:latest
    docker push aadilsehrawat/aadils-docker-image:latest
  displayName: 'Docker Push'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    appType: 'webAppLinux'
    WebAppName: 'StreamlineSolutions'
    packageForLinux: $(Pipeline.Workspace)
    RuntimeStack: 'DOCKER|latest'
    StartupCommand: ''
