name: ci

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Pull Docker Image
        run: docker pull ${{ secrets.DOCKERHUB_USERNAME }}/aadils-docker-image:latest

      -
        name: Deploy to Azure Web App
        env:
          AZURE_WEBAPP_NAME: StreamlineSolutions # Replace with your Azure Web App name
          DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/aadils-docker-image:latest
        run: |
          az webapp config container set --name $AZURE_WEBAPP_NAME --resource-group newrg --docker-custom-image-name $DOCKER_IMAGE --docker-registry-server-url https://index.docker.io

